version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: "sonarcloud/codebuild-token"  # From AWS Secrets Manager

phases:
  install:
    runtime-versions:
      java: corretto11  # Amazon Corretto JDK 11
    commands:
      - echo "Installing dependencies..."
      - chmod +x gradlew
      - ./gradlew dependencies

  pre_build:
    commands:  # <- This line must be indented under pre_build
      - echo "Running SonarCloud preparation..."
      - export SONAR_SCANNER_OPTS='-Dsonar.projectKey=seun-technologies1 -Dsonar.organization="Seun Technologies" -Dsonar.host.url=https://sonarcloud.io'

  build:
    commands:
      - echo "Building the project..."
      - ./gradlew clean build

  post_build:
    commands:
      - echo "Running SAST Scan with SonarCloud..."
      - ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN
      - echo "SAST Scan Completed! Check SonarCloud Dashboard."